on:
  workflow_dispatch:
  push:
    branches:
      - master
      - release/*
  pull_request:

name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Dependencies
        run: sudo apt update -y && sudo apt install libgpgme11-dev libgpg-error-dev nettle-dev -y
      - uses: actions-rs/cargo@v1
        with:
          command: check

  ubuntutest:
    name: Test Suite on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Dependencies
        run: sudo apt update -y && sudo apt install libssl-dev libclang-dev libadwaita-1-dev libgpgme11-dev libgpg-error-dev libgtk-4-dev libxcb-shape0-dev libxcb-xfixes0-dev nettle-dev -y
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all

  macostest:
    name: Test Suite on MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install dependencies
        run: |
          brew update || true
          brew install gpgme nettle || true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p ripasso-cursive

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - name: Dependencies
        run: sudo apt update -y && sudo apt install libgpgme11-dev libgpg-error-dev nettle-dev -y
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - name: Dependencies
        run: sudo apt update -y && sudo apt install libgpgme11-dev libgpg-error-dev nettle-dev -y
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  audit:
    name: Audit
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/audit@v1
        name: Audit Rust Dependencies
  
  flatpak:
    name: Build Flatpak bundle
    runs-on: ubuntu-latest
    needs: check
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Generate lockfile
        run: cargo generate-lockfile --offline

      - name: Install flatpak-builder-tools
        run: pip install --user flatpak-builder-tools
      - name: Generate sources JSON
        run: |
          flatpak-cargo-generator.py \
            --lockfile Cargo.lock \
            --output ripasso-sources.json

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: io.github.cortex.Ripasso.yml
          bundle: ripasso.flatpak
          cache-key: flatpak-${{ github.sha }}

      - uses: actions/upload-artifact@v4
        with:
          name: ripasso.flatpak
          path: ripasso.flatpak
